name: Notificar cambio a n8n

on:
  push:
    paths:
      - 'documentacion/base_datos.json'

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Llamar Webhook
        run: |
          curl -X POST https://tu-instancia-n8n.com/webhook/github-update
          echo test, and deploy your project.
