name: Notificar cambio a n8n

on:
  push:
    paths:
      - 'documentation.md'

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Llamar Webhook
        run: |
          curl -X POST  https://lawsuit-mounts-options-ethical.trycloudflare.com/webhook-test/github-update \
            -H "Content-Type: application/json" \
            -d '{"event": "documentation_updated", "file": "documentation.md"}
    
