name: Notificar cambio a n8n

on:
  push:
    paths:
      - 'documentacion/base_datos.json'

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Llamar Webhook
        run: |
          curl -X POST https://berry-dave-judges-montreal.trycloudflare.com/webhook/f9df7885-2905-4f82-a169-333a410fc70b/webhook/github-update
          echo test, and deploy your project.
